{
 "title": "Consensus-1",
 "time": { "from": "2020-06-16T18:01:51.808Z", "to": "2020-06-16T18:02:11.948Z" },
 "panels": [
  {
   "title": "General Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Committed blocks per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "blocks per sec" }
     ],
     "targets": [
      {
       "expr": "irate(libra_consensus_last_committed_round[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Committed successful txns per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(libra_consensus_last_committed_version[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Block creation to vote / QC / commit",
     "type": "graph",
     "description": "Duration between block generation time until the moment it is first received by a voter / gathers full QC",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "s" }
     ],
     "targets": [
      {
       "expr": "irate(libra_consensus_creation_to_qc_s_sum[1m])/irate(libra_consensus_creation_to_qc_s_count[1m])",
       "legendFormat": "{{peer_id}}: QC"
      },
      {
       "expr": "irate(libra_consensus_creation_to_receival_s_sum[1m])/irate(libra_consensus_creation_to_receival_s_count[1m])",
       "legendFormat": "{{peer_id}}: vote"
      },
      {
       "expr": "irate(libra_consensus_creation_to_commit_s_sum[1m])/irate(libra_consensus_creation_to_commit_s_count[1m])",
       "legendFormat": "{{peer_id}: commit"
      }
     ]
    },
    {
     "title": "Event Loop Idle Percent",
     "type": "graph",
     "description": "Percent of time the main Event Loop spends idle",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit", "label": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(libra_consensus_event_processing_loop_idle_duration_s_sum[1m]) /  (irate(libra_consensus_event_processing_loop_idle_duration_s_sum[1m]) +  irate(libra_consensus_event_processing_loop_busy_duration_s_sum[1m]))",
       "legendFormat": "{{peer_id}} Idle"
      }
     ]
    }
   ]
  },
  {
   "title": "RoundState",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Round",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "libra_consensus_current_round", "legendFormat": "{{peer_id}}" }
     ]
    },
    {
     "title": "Total timeout rounds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "count timeout rounds" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_timeout_rounds_count",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total local timeout",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "count timeouts" }
     ],
     "targets": [
      { "expr": "libra_consensus_timeout_count", "legendFormat": "{{peer_id}}" }
     ]
    },
    {
     "title": "Total QC rounds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "rounds per sec" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_qc_rounds_count",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Round timeout val",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ms", "label": "timeout val (ms)" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_round_timeout_s",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EpochState",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Epoch",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "libra_consensus_epoch", "legendFormat": "{{peer_id}}" }
     ]
    },
    {
     "title": "Number of validators",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_current_epoch_validators",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BlockStore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_num_blocks_in_tree - 1",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Transactions per block",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(libra_consensus_num_txns_per_block_sum[1m])/irate(libra_consensus_num_txns_per_block_count[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total wait duration",
     "type": "graph",
     "description": "Total time the node has to wait before inserting the block",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_wait_duration_s_sum",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "State Synchronization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "State sync count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "count state sync" }
     ],
     "targets": [
      {
       "expr": "consensus_duration_count{op='sync_to'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total time spent on state sync",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "s", "label": "total time spent (s)" }
     ],
     "targets": [
      {
       "expr": "consensus_duration_sum{op='sync_to'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total sync info sent to help peers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_sync_info_msg_sent_count",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Block retrieval count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "count" }
     ],
     "targets": [
      {
       "expr": "consensus_duration_count{op='block_retrieval'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total time spent on block retrieval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "total time spent (s)" }
     ],
     "targets": [
      {
       "expr": "consensus_duration_sum{op='block_retrieval'}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Proposer Election",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proposals rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "/s" }
     ],
     "targets": [
      {
       "expr": "irate(libra_consensus_proposals_count[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total vote on Nil",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "/s" }
     ],
     "targets": [
      { "expr": "libra_consensus_vote_nil_count", "legendFormat": "{{peer_id}}" }
     ]
    }
   ]
  },
  {
   "title": "SafetyState",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last voted round",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_last_vote_round",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Preferred round",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_preferred_block_round",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Message queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network -> Consensus",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_pending_network_events{state=\"dequeued\"}",
       "legendFormat": "{{peer_id}}: dequeued"
      },
      {
       "expr": "libra_consensus_pending_network_events{state=\"enqueued\"}",
       "legendFormat": "{{peer_id}}: enqueued"
      },
      {
       "expr": "libra_consensus_pending_network_events{state=\"dropped\"}",
       "legendFormat": "{{peer_id}}: dropped"
      }
     ]
    },
    {
     "title": "Consensus -> Main loop (Consensus Msg)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_channel_msgs_count{state=\"dequeued\"}",
       "legendFormat": "{{peer_id}}: dequeued"
      },
      {
       "expr": "libra_consensus_channel_msgs_count{state=\"enqueued\"}",
       "legendFormat": "{{peer_id}}: enqueued"
      },
      {
       "expr": "libra_consensus_channel_msgs_count{state=\"dropped\"}",
       "legendFormat": "{{peer_id}}: dropped"
      }
     ]
    },
    {
     "title": "Consensus -> Main loop (Block retrieval)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_block_retrieval_channel_msgs_count{state=\"dequeued\"}",
       "legendFormat": "{{peer_id}}: dequeued"
      },
      {
       "expr": "libra_consensus_block_retrieval_channel_msgs_count{state=\"enqueued\"}",
       "legendFormat": "{{peer_id}}: enqueued"
      },
      {
       "expr": "libra_consensus_block_retrieval_channel_msgs_count{state=\"dropped\"}",
       "legendFormat": "{{peer_id}}: dropped"
      }
     ]
    },
    {
     "title": "Pending self message & local timeout",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "libra_consensus_pending_self_messages",
       "legendFormat": "{{peer_id}}: self message"
      },
      {
       "expr": "libra_consensus_pending_round_timeouts",
       "legendFormat": "{{peer_id}}: timeout"
      }
     ]
    }
   ]
  }
 ]
}